# Generated by Django 4.1.2 on 2023-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230604_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos_list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
